---
title: "2026-08-17 Kynningarefni"
description: >-
  Quarto-glærur námskeiðsins sem opnast sem sérstakar HTML-kynningar.
---

Hér eru Quarto-glærur sem eru notaðar í fyrsta tíma. Glærurnar opnast sem sérstök HTML-kynning.

::: {.lotu-list}

::: {.lotu-card}
### 2026-08-17 Kynningarefni

Fyrsti tími og stutt yfirlit yfir námskeiðið, vinnuflæðið, GitHub, erindreka og capstone-verkefnið.

[Opna intro-glærur](intro.html)
:::

:::

## Tengt efni

Eftirfarandi efni tengist námskeiðinu óbeint og sýnir hluta af þeirri kennsluhönnun
sem IÐN302G byggir á.

- [CDIO-BI](https://github.com/tungufoss/CDIO-BI) tengist námskeiðshönnun í
  viðskiptagreind (IÐN610M) og lýsir núverandi nálgun á upplýsingaverkfræði:
  Ingimundardóttir, H. (2026). *Designing authentic industry-engaged assessment for
  professional competence in business intelligence*. Proceedings of the 22nd
  International CDIO Conference. CDIO Initiative, Liverpool, United Kingdom.
- [CDIO-GitHub](https://github.com/tungufoss/CDIO-GitHub) fjallar um hvernig pull
  requests geta gert samstarf sýnilegt í verkefnamiðuðum námskeiðum:
  Ingimundardóttir, H. (2026). *Using pull requests to make collaboration visible in
  CDIO project-based courses*. Proceedings of the 22nd International CDIO Conference.
  CDIO Initiative, Liverpool, United Kingdom.
