project:
  type: book
  output-dir: docs

book:
  title: "Upplýsingaverkfræði IÐN302G"
  author: "Háskóli Íslands"
  language: is
  repo-url: https://github.com/HI-IDN/IDN302G
  repo-actions: [edit, issue]
  site-url: https://hi-idn.github.io/IDN302G
  favicon: img/hi/favicon.svg
  search: true
  navbar:
    logo: img/hi/hi_named_logo-is.svg
    logo-alt: "Háskóli Íslands"
  sidebar:
    style: docked
    background: light
  chapters:
    - index.qmd
    - part: "SQL grunnatriði"
      chapters:
        - src/sql-basics/introduction.md
        - src/sql-basics/basic_sql_queries.md
        - src/sql-basics/tables.md
        - src/sql-basics/aggregation_and_grouping.md
        - src/sql-basics/null.md
        - src/sql-basics/subquery.md
        - src/sql-basics/data_integrity.md
        - src/sql-basics/import_export_data.md
        - src/sql-basics/script_files.md
        - src/sql-basics/database_interaction.md
        - src/sql-basics/exercises.md
        - src/sql-basics/additional_resources.md
    - part: "SQL framhald"
      chapters:
        - src/sql-advanced/introduction.md
        - src/sql-advanced/postgres.md
        - src/sql-advanced/union.md
        - src/sql-advanced/joins.md
        - src/sql-advanced/views.md
        - src/sql-advanced/functions.md
        - src/sql-advanced/cte.md
        - src/sql-advanced/postgis.md
    - part: "Myndræn framsetning"
      chapters:
        - src/storytelling/introduction.md
        - src/storytelling/lightning_talk.md
        - src/storytelling/visuals_major.md
        - src/storytelling/visuals_minor.md
        - src/storytelling/interactive.md
        - src/storytelling/dashboard.md
        - src/storytelling/donts.md
        - src/storytelling/data_narrative.md
        - src/storytelling/additional_resources.md

format:
  html:
    theme:
      - cosmo
      - styles/hi-book.scss
    include-in-header: partials/header-includes.inc
    toc: true
    toc-depth: 3
    lang: is
