{
  "hash": "9d5d3d6c4754fa187e23122e9a120a6b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Opnar vefþjónustur\"\ndescription: >-\n  Tvö raunveruleg dæmi um þjónustur sem má prófa án aðgangslykils:\n  Hagstofan (POST með fyrirspurn, json-stat2) og Veðurstofan (GET, OpenAPI-skjölun).\nexecute:\n  freeze: true\n---\n\nHingað til hafa dæmin snúist um GitHub. Hér eru tvær opnar íslenskar þjónustur sem þú getur notað í verkefnum án þess að sækja fyrst um lykil. Þær sýna mynstur sem GitHub gerir ekki: fyrirspurn send með `POST`, og formleg vélleshæf skjölun.\n\n## Hagstofan\n\nHagstofan keyrir **PxWeb**, sama kerfi og hagstofur á Norðurlöndunum. Það er ólíkt GitHub að\nþví leyti að þú sækir gögnin með `POST`, ekki `GET`: taflan getur verið risastór, svo þú sendir\ninn *fyrirspurn* um hvaða sneið þú vilt.\n\n### Fyrst: hvað er í töflunni?\n\nGagnasöfnin eru í tré sem þú getur flakkað um. Efsta lagið:\n\n```\nhttps://px.hagstofa.is/pxis/api/v1/is/\n```\n\nHver `GET` skilar möppum þar til þú lendir á töflu — skrá sem endar á `.px`. Við notum\nlykiltölur mannfjöldans:\n\n```\nhttps://px.hagstofa.is/pxis/api/v1/is/Ibuar/mannfjoldi/1_yfirlit/Yfirlit_mannfjolda/MAN00000.px\n```\n\n`GET` á töfluna sjálfa skilar **lýsigögnum** (e. *metadata*) — hvaða breytur eru í boði og\nhvaða gildi þær mega taka:\n\n``` json\n{\n  \"title\": \"Lykiltölur mannfjöldans 1703-2026\",\n  \"variables\": [\n    { \"code\": \"Ár\", \"text\": \"Ár\", \"values\": [\"1703\", \"1734\", \"…\", \"2026\"], \"time\": true },\n    { \"code\": \"Eining\", \"text\": \"Eining\",\n      \"values\": [\"0\", \"1\", \"2\", \"3\", \"4\", \"5\"],\n      \"valueTexts\": [\"Mannfjöldi 1. janúar\", \"Árleg fjölgun\", \"Fjölgun\",\n                     \"Aðfluttir umfram brottflutta\", \"Fæddir umfram dána\",\n                     \"Leiðréttingarþáttur\"] }\n  ]\n}\n```\n\n::: {.callout-important}\n## Lestu lýsigögnin fyrst\n\nTaktu eftir að `values` eru **kóðar** (`\"0\"`) en `valueTexts` eru **heitin** (`\"Mannfjöldi 1.\njanúar\"`). Í fyrirspurninni notar þú kóðana, ekki heitin. Þetta er algengasta ástæðan fyrir því\nað fyrsta PxWeb-fyrirspurnin skilar villu.\n:::\n\n### Svo: fyrirspurnin\n\n`POST` á sömu slóð með JSON-hlut sem segir hvaða gildi þú vilt:\n\n``` json\n{\n  \"query\": [\n    { \"code\": \"Ár\",     \"selection\": { \"filter\": \"item\",\n                                       \"values\": [\"2020\",\"2021\",\"2022\",\"2023\",\"2024\",\"2025\",\"2026\"] } },\n    { \"code\": \"Eining\", \"selection\": { \"filter\": \"item\", \"values\": [\"0\"] } }\n  ],\n  \"response\": { \"format\": \"json-stat2\" }\n}\n```\n\n::: {.panel-tabset}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(httr2)\n\nslod <- paste0(\"https://px.hagstofa.is/pxis/api/v1/is/Ibuar/mannfjoldi/\",\n               \"1_yfirlit/Yfirlit_mannfjolda/MAN00000.px\")\n\nlysing <- request(slod) |>\n  req_user_agent(\"IDN302G-nemandi (nafn@hi.is)\") |>\n  req_perform() |>\n  resp_body_json(simplifyVector = FALSE)\n\nfyrirspurn <- list(\n  query = list(\n    list(code = lysing$variables[[1]]$code,\n         selection = list(filter = \"item\",\n                          values = as.character(2020:2026))),\n    list(code = lysing$variables[[2]]$code,\n         selection = list(filter = \"item\", values = list(\"0\")))\n  ),\n  response = list(format = \"json-stat2\")\n)\n\nsvar <- request(slod) |>\n  req_user_agent(\"IDN302G-nemandi (nafn@hi.is)\") |>\n  req_body_json(fyrirspurn) |>\n  req_perform()\n\nresp_status(svar)\nd <- resp_body_json(svar, simplifyVector = TRUE)\nstr(d, max.level = 1)\n```\n:::\n\n\nTaktu eftir `$value`: tölurnar sjö sem þú baðst um eru þarna, en árin sjálf eru í `$dimension`.\nÞað er einkenni json-stat2 og efni næsta undirkafla.\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport requests\n\nslod = (\"https://px.hagstofa.is/pxis/api/v1/is/Ibuar/mannfjoldi/\"\n        \"1_yfirlit/Yfirlit_mannfjolda/MAN00000.px\")\n\nfyrirspurn = {\n    \"query\": [\n        {\"code\": \"Ár\",\n         \"selection\": {\"filter\": \"item\",\n                       \"values\": [str(a) for a in range(2020, 2027)]}},\n        {\"code\": \"Eining\",\n         \"selection\": {\"filter\": \"item\", \"values\": [\"0\"]}},\n    ],\n    \"response\": {\"format\": \"json-stat2\"},\n}\n\nsvar = requests.post(\n    slod,\n    json=fyrirspurn,                       # setur Content-Type sjálfkrafa\n    headers={\"User-Agent\": \"IDN302G-nemandi (nafn@hi.is)\"},\n    timeout=30,\n)\nsvar.raise_for_status()\nd = svar.json()\n\nprint(svar.status_code)\nprint(list(d.keys()))\nprint(d[\"value\"])\n```\n:::\n\n\nSama svar og R fær — enda er þetta sama JSON-skjalið. Munurinn er aðeins hvernig málin\ntvö birta það: R sem `List of 11`, Python sem `dict` með ellefu lyklum.\n\nTaktu eftir `json=` frekar en `data=` — `requests` raðar hlutnum sjálft í JSON og setur réttan\n`Content-Type`. Með `data=` þyrftirðu að gera hvort tveggja handvirkt.\n:::\n\n### Að lesa json-stat2\n\nSvarið er á sniðinu **json-stat2**, sem geymir tölurnar í einum flötum vigri og víddirnar\nsérstaklega. Það kemur á óvart í fyrsta sinn:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(jsonlite)\n\n# Raunverulegt svar, stytt — sótt af Hagstofunni\nsvar_txt <- '{\n  \"label\": \"Lykiltölur mannfjöldans 1703-2026 by Ár og Eining\",\n  \"size\": [7, 1],\n  \"dimension\": {\n    \"Ár\": { \"category\": { \"index\": {\"2020\":0,\"2021\":1,\"2022\":2,\"2023\":3,\n                                    \"2024\":4,\"2025\":5,\"2026\":6},\n                          \"label\": {\"2020\":\"2020\",\"2021\":\"2021\",\"2022\":\"2022\",\"2023\":\"2023\",\n                                    \"2024\":\"2024\",\"2025\":\"2025\",\"2026\":\"2026\"} } },\n    \"Eining\": { \"category\": { \"label\": {\"0\": \"Mannfjöldi 1. janúar\"} } }\n  },\n  \"value\": [354042, 358298, 364917, 375218, 383726, 389444, 394324]\n}'\n\nd <- fromJSON(svar_txt)\nd$label\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Lykilt<U+00F6>lur mannfj<U+00F6>ldans 1703-2026 by <U+00C1>r og Eining\"\n```\n\n\n:::\n\n```{.r .cell-code}\nd$size\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7 1\n```\n\n\n:::\n:::\n\n\nTölurnar eru í `value`, og heiti áranna í `dimension`. Að setja þetta saman í töflu:\n\n::: {.panel-tabset}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# d$id skilgreinir rod viddanna i json-stat2 þegar reiturinn er til staðar.\n# Í styttu sýnidæmi notum við fyrsta dimension-lykilinn í staðinn.\n# index gefur svo stodu hvers ars i value-vigrinum.\nar_kodi <- if (!is.null(d$id) && length(d$id) > 0) d$id[1] else names(d$dimension)[1]\nidx <- unlist(d$dimension[[ar_kodi]]$category$index)\nar  <- names(idx)[order(idx)]\n\nmannfjoldi <- data.frame(ar = as.integer(ar), mannfjoldi = d$value)\nmannfjoldi\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    ar mannfjoldi\n1 2020     354042\n2 2021     358298\n3 2022     364917\n4 2023     375218\n5 2024     383726\n6 2025     389444\n7 2026     394324\n```\n\n\n:::\n:::\n\n\nÞaðan er þetta venjuleg gagnavinnsla:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n\nmannfjoldi |>\n  mutate(fjolgun = mannfjoldi - lag(mannfjoldi),\n         hlutfall = round(fjolgun / lag(mannfjoldi) * 100, 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    ar mannfjoldi fjolgun hlutfall\n1 2020     354042      NA       NA\n2 2021     358298    4256     1.20\n3 2022     364917    6619     1.85\n4 2023     375218   10301     2.82\n5 2024     383726    8508     2.27\n6 2025     389444    5718     1.49\n7 2026     394324    4880     1.25\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\n\n# index gefur stöðu hvers árs í value-listanum. Röðun label-hlutarins er\n# ekki skilgreind í JSON og má ekki treysta á hana.\ncat = d[\"dimension\"][\"Ár\"][\"category\"]\nar = [k for k, _ in sorted(cat[\"index\"].items(), key=lambda kv: kv[1])]\n\nmannfjoldi = pd.DataFrame({\n    \"ar\": [int(a) for a in ar],\n    \"mannfjoldi\": d[\"value\"],\n})\n\nmannfjoldi[\"fjolgun\"] = mannfjoldi[\"mannfjoldi\"].diff()\nmannfjoldi[\"hlutfall\"] = (mannfjoldi[\"fjolgun\"] /\n                          mannfjoldi[\"mannfjoldi\"].shift() * 100).round(2)\nmannfjoldi\n```\n:::\n\n\n`diff()` og `shift()` gegna sama hlutverki og `lag()` í R.\n\nTaktu eftir tvennu sem er ólíkt R-flipanum: `pandas` sýnir `NaN` þar sem R sýnir `NA`, og\n`fjolgun` verður **kommutala** (`4256.0`) en ekki heiltala. Ástæðan er að `NaN` er\nfleytitölugildi í `numpy`, svo heiltöludálkur með einu `NaN` breytist allur í fleytitölur.\nÞurfirðu heiltölur áfram má nota `.astype(\"Int64\")` — stóra I-ið gefur heiltölugerð sem\nþolir tómt gildi.\n:::\n\n::: {.callout-tip}\n## Einfaldari leið\n\nSé json-stat2 fyrirhöfnin ekki þess virði geturðu beðið um `\"format\": \"csv\"` í stað\n`\"json-stat2\"` og lesið svarið beint með `readr::read_csv()`. Þú tapar lýsigögnunum en færð\ntöflu strax.\n:::\n\n## Veðurstofan\n\nVeðurstofan býður `GET`-þjónustu á `api.vedur.is`, og með henni **formlega skjölun** á\n[api.vedur.is/weather](https://api.vedur.is/weather/).\n\nSú síða er [Swagger UI](https://swagger.io/open-source/swagger-ui/), sjálfvirkt viðmót byggt á **OpenAPI**-skilgreiningu: vélleshæfri\nlýsingu á öllum endapunktum þjónustunnar. Skilgreininguna sjálfa má sækja:\n\n```\nhttps://api.vedur.is/weather/openapi.json\n```\n\n::: {.callout-note}\n## Af hverju OpenAPI skiptir máli\n\nÞegar þjónusta birtir OpenAPI-skrá þarftu ekki að giska. Þar stendur hver endapunktur, hvaða\nfæribreytur hann tekur, hvað hann skilar og hvaða stöðukóðar eru mögulegir. Mörg tól geta lesið\nhana og búið til kóða sjálfkrafa. Sé slík skrá til, byrjaðu þar.\n:::\n\nEinfaldur endapunktur — listi yfir veðurstöðvar. Skjölunin segir að hann taki `station_id`,\nsvo við biðjum um þrjár tilteknar stöðvar:\n\n```\nhttps://api.vedur.is/weather/stations?station_id=1&station_id=422&station_id=1350\n```\n\nÞessa slóð máttu opna beint í vafra. Svarið er fylki af hlutum:\n\n``` json\n[\n  {\n    \"station\": 1,\n    \"name\": \"Reykjavík\",\n    \"abbr\": \"rvk\",\n    \"type\": \"sk\",\n    \"lat\": 64.1288833618,\n    \"lon\": -21.9081897736,\n    \"ele\": 60.2000007629,\n    \"wigos\": \"0-20000-0-04030\",\n    \"owner\": \"Veðurstofa Íslands\",\n    \"start\": 1920,\n    \"ending\": null\n  },\n  …\n]\n```\n\nFylki af hlutum með sömu lykla er einmitt formið sem verður að töflu án fyrirhafnar:\n\n::: {.panel-tabset}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(httr2); library(dplyr)\n\nstodvar <- request(\"https://api.vedur.is/weather/stations\") |>\n  req_url_query(station_id = c(1, 178, 1350), .multi = \"explode\") |>\n  req_user_agent(\"IDN302G-nemandi (nafn@hi.is)\") |>\n  req_perform() |>\n  resp_body_json(simplifyVector = TRUE)\n\nstodvar |>\n  select(station, name, lat, lon, ele, start)\n```\n:::\n\n\n`.multi = \"explode\"` endurtekur `station_id=` fyrir hvert gildi, sem er það sem þessi þjónusta\nbýst við.\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport requests\nimport pandas as pd\n\nsvar = requests.get(\n    \"https://api.vedur.is/weather/stations\",\n    params={\"station_id\": [1, 178, 1350]},\n    headers={\"User-Agent\": \"IDN302G-nemandi (nafn@hi.is)\"},\n    timeout=30,\n)\nsvar.raise_for_status()\n\nstodvar = pd.DataFrame(svar.json())\nstodvar[[\"station\", \"name\", \"lat\", \"lon\", \"ele\", \"start\"]]\n```\n:::\n\n\nListi sem gildi í `params` verður sjálfkrafa að endurteknu `station_id=` í slóðinni.\n:::\n\n::: {.callout-important}\n## Óþekktar færibreytur eru þagðar í hel\n\nSleppirðu `station_id` skilar endapunkturinn **öllum 776 stöðvunum**. Og biðjirðu um eitthvað\nsem er ekki til — `?limit=3` til dæmis — færðu líka allar 776. Þjónustan hunsar færibreytu sem\nhún þekkir ekki, svarar `200`, og ekkert bendir til að nokkuð sé að.\n\nÞetta er nákvæmlega gildran úr [HTTP-kaflanum](http.qmd): `200` þýðir að samskiptin gengu, ekki\nað þú hafir fengið það sem þú baðst um. Athugaðu alltaf **hversu margar færslur** komu til baka\nog berðu saman við það sem þú bjóst við.\n:::\n\n## Prófaðu sjálf/ur — lifandi svar\n\nHnappurinn hér að neðan sendir raunverulega beiðni á Veðurstofuna **úr vafranum þínum** og\nsýnir svarið óbreytt. Þetta er sama beiðni og R-kóðinn að ofan sendir:\n\n```{=html}\n<div class=\"api-demo\">\n  <div class=\"api-demo-url\"><code>GET https://api.vedur.is/weather/stations?station_id=1&amp;station_id=422</code></div>\n  <button id=\"api-demo-btn\" class=\"api-demo-btn\" type=\"button\" aria-controls=\"api-demo-out\" aria-describedby=\"api-demo-status\">Senda beiðni</button>\n  <span id=\"api-demo-status\" class=\"api-demo-status\" role=\"status\" aria-live=\"polite\"></span>\n  <pre id=\"api-demo-out\" class=\"api-demo-out\" hidden aria-live=\"polite\" aria-label=\"Svar frá vefþjónustu\"></pre>\n</div>\n\n<style>\n.api-demo{border:1px solid #ddd;border-radius:8px;padding:1em;margin:1.2em 0;background:#fafafa}\n.api-demo-url{font-size:.85rem;margin-bottom:.7em;color:#444}\n.api-demo-btn{font:inherit;font-weight:600;cursor:pointer;border:1px solid #10099F;\n  background:#10099F;color:#fff;padding:.4em 1em;border-radius:6px}\n.api-demo-btn:hover{filter:brightness(1.15)}\n.api-demo-btn[disabled]{opacity:.6;cursor:progress}\n.api-demo-status{margin-left:.8em;font-size:.88rem;font-weight:600}\n.api-demo-status.ok{color:#1a9b8d} .api-demo-status.err{color:#b03a24}\n.api-demo-out{margin-top:.8em;max-height:22em;overflow:auto;background:#262626;color:#eee;\n  padding:.8em 1em;border-radius:6px;font-size:.82rem;line-height:1.45}\n</style>\n\n<script>\ndocument.getElementById('api-demo-btn').addEventListener('click', async function () {\n  const btn = this;\n  const out = document.getElementById('api-demo-out');\n  const st  = document.getElementById('api-demo-status');\n  btn.disabled = true;\n  st.className = 'api-demo-status';\n  st.textContent = 'Sendi…';\n  const t0 = performance.now();\n  try {\n    const r = await fetch('https://api.vedur.is/weather/stations?station_id=1&station_id=422');\n    const ms = Math.round(performance.now() - t0);\n    const txt = await r.text();\n    st.className = 'api-demo-status ' + (r.ok ? 'ok' : 'err');\n    st.textContent = (r.statusText ? r.status + ' ' + r.statusText : String(r.status))\n                   + ' · ' + ms + ' ms';\n    try { out.textContent = JSON.stringify(JSON.parse(txt), null, 2); }\n    catch (e) { out.textContent = txt; }\n    out.hidden = false;\n  } catch (e) {\n    st.className = 'api-demo-status err';\n    st.textContent = 'Beiðnin komst ekki á leiðarenda: ' + e.message;\n    out.textContent = 'Þjónustan gæti verið niðri, eða netið lokað á hana.';\n    out.hidden = false;\n  } finally {\n    btn.disabled = false;\n  }\n});\n</script>\n```\n\n::: {.callout-note}\n## Af hverju þetta virkar í vafranum\n\nVafrar banna vefsíðu að sækja gögn af öðru léni nema þjónustan leyfi það sérstaklega. Það\nheitir **CORS** (*Cross-Origin Resource Sharing*), og þjónustan gefur leyfið með hausnum\n`Access-Control-Allow-Origin`. Veðurstofan sendir `*`, sem þýðir \"hver sem er má\".\n\nSendi þjónusta ekki þann haus færðu villu í vafranum þótt slóðin sé rétt — og *sama* beiðni\nvirkar samt fínt úr R eða `curl`. CORS er regla vafrans, ekki þjónustunnar. Rekist þú á\n`CORS error` í vafranum en ekki í R, þá er það þetta.\n:::\n\n## Æfingar\n\nTvær æfingar, ein á hvora þjónustu. Báðar enda á sama stað: **er svarið sem þú fékkst\nraunverulega nothæft?**\n\n::: {.callout-note}\n## Tölurnar hér að neðan eru fryst kennsluúttak\n\nNiðurstöðurnar sem fylgja hvorri æfingu eru dæmi um úttak úr þjónustunum. Lifandi köll eru ekki keyrð í sjálfri bókarbyggingunni, því opnar þjónustur geta tímabundið svarað með `429 Too Many Requests` þegar margir byggja eða prófa í einu.\n\nÞað þýðir tvennt. Þú átt að geta fengið sömu gerð af svari þegar þú keyrir kóðann sjálf/ur, en þú þarft alltaf að bera tölurnar saman við nýjustu gögnin. Veðurstöðvum fjölgar og fækkar, og brautskráningartölur eru endurskoðaðar. Tala sem er slegin inn með höndunum verður þögul ósannindi um leið og gögnin hreyfast.\n:::\n\n### 1. Hagstofan — hverjir klára BS-námið?\n\nHversu stór hluti þeirra sem byrja í þriggja ára bakkalárnámi í verkfræði lýkur því? Og er\nþað hlutfall hærra eða lægra en í öðrum greinum?\n\nTaflan heitir **SKO04208b**, *Brautskráningarhlutfall og árgangsbrotthvarf í þriggja ára\nbakkalárnámi eftir námssviði*:\n\n```\nhttps://px.hagstofa.is/pxis/api/v1/is/Samfelag/skolamal/4_haskolastig/1_hsProf/SKO04208b.px\n```\n\n1. Sæktu lýsigögnin með `GET`. Hvaða breytur eru í boði og hvaða gildi mega þær taka?\n2. Finndu kóðann fyrir *Verkfræði, framleiðsla og mannvirkjagerð* — mundu að nota **kóðana**\n   úr `values`, ekki heitin úr `valueTexts`.\n3. Sendu `POST` og sæktu **hlutfall** (ekki fjölda) fyrir brautskráða, brottfallna og þá sem\n   eru enn í námi, fyrir innritunarárið 2017.\n4. Berðu verkfræðisviðið saman við `Alls` og við tvö önnur svið að eigin vali.\n\nNiðurstaðan lítur svona út:\n\n\n::: {.cell}\n\n:::\n\n\n::: {.callout-important}\n## Lestu `Tími` áður en þú túlkar töluna\n\nBreytan `Tími` hefur eitt gildi: `n+3`, sem `valueTexts` þýðir sem **„Sex árum eftir\ninnritun\"**.\n\nÞessi 84,3% eru því ekki hlutfall þeirra sem kláruðu **á þremur árum** — heldur þeirra sem\nvoru búnir **sex árum** eftir að þeir byrjuðu. Það er allt önnur fullyrðing, og hún stendur\nhvergi í tölunni sjálfri.\n\nFullyrðing eins og „84% verkfræðinema klára á réttum tíma\" væri því röng, byggð á réttum\ngögnum. Lýsigögnin ráða því hvað talan þýðir.\n:::\n\nSvaraðu svo:\n\n5. Hvers vegna leggja dálkarnir þrír saman í 100?\n6. Innritunarárin í töflunni eru aðeins **tvö** (2014 og 2017). Hvers vegna er varasamt að\n   draga ályktun um þróun út frá tveimur punktum?\n7. Sæktu sömu tölur skipt eftir kyni. Breytist myndin?\n\n### 2. Veðurstofan — hvaða stöð á forritið að lesa?\n\nSegjum að þú ætlir að smíða lítið forrit sem sýnir veðrið uppi í skóla. Fyrsta spurningin er:\n**hvaða veðurstöð á það að lesa?**\n\nAugljósa svarið er sú sem er næst VR-II (Hjarðarhaga 6, 107 Reykjavík). En áður en þú byggir\nforritið á því svari þarftu að ganga úr skugga um að það sé **nothæft** — stöð sem hætti\nmælingum 1963 er jafn nálæg og hún var, og jafn gagnslaus.\n\n**Finndu hnitin.** Þú getur flett þeim upp með annarri vefþjónustu,\n[Nominatim](https://nominatim.openstreetmap.org/) frá OpenStreetMap:\n\n```\nhttps://nominatim.openstreetmap.org/search?q=Hjarðarhagi+6,+107+Reykjavík&format=json\n```\n\n**Síaðu í beiðninni, ekki eftir á.** Endapunkturinn skilar 776 stöðvum sé hann beðinn um allt.\nSkjölunin sýnir tvær færibreytur sem gera vinnuna fyrir þig:\n\n| Færibreyta | Hvað hún gerir |\n|---|---|\n| `active=true` | aðeins stöðvar sem mæla enn |\n| `polygon=POLYGON((…))` | aðeins stöðvar innan tiltekins svæðis |\n\n```\nhttps://api.vedur.is/weather/stations\n  ?active=true\n  &polygon=POLYGON((-22.0589 64.0936,-21.8524 64.0936,-21.8524 64.1837,-22.0589 64.1837,-22.0589 64.0936))\n```\n\nBerðu saman hvað kemur til baka:\n\n\n::: {.cell}\n\n:::\n\n\nÚr mörg hundruð stöðvum niður í örfáar — og þú reiknar fjarlægð á þær í stað allra hinna.\n\n::: {.callout-note}\n## Hvaðan kemur marghyrningurinn?\n\nÞú teiknar hann sjálf/ur: kassi utan um punktinn, radíus umreiknaður í gráður. Breiddargráða er\nalls staðar ~111 km, en lengdargráða styttist í $111\\cos\\varphi$ — aðeins ~49 km á Íslandi, svo\nkassinn er breiðari í lengd en breidd.\n\nFyrir 5 km um VR-II gefur það `POLYGON((-22.0589 64.0936, -21.8524 64.0936, -21.8524 64.1837,\n-22.0589 64.1837, -22.0589 64.0936))` — og **9 virkar stöðvar**.\n:::\n\n::: {.callout-tip}\n## Tvennt til að hafa hugfast sem gæti annars valdið villu\n\n**Hnitaröðin er `lengd breidd`** (e. *lon lat*) — öfugt við `lat,lon` sem flestar þjónustur\nskila. Marghyrningurinn þarf líka að lokast: fyrsta og síðasta hnitið eru þau sömu.\n\n**`boundingbox` frá Nominatim dugar ekki.** Fyrir heimilisfang er hann kassi utan um bygginguna\nsjálfa — um 60 m á kant fyrir VR-II — svo hann finnur enga veðurstöð.\n:::\n\n**Reiknaðu fjarlægðina** með\n[haversine-formúlunni](https://en.wikipedia.org/wiki/Haversine_formula), sem gefur stórbaugsfjarlægð milli tveggja hnita á kúlu:\n\n$$\nd = 2r \\arcsin\\!\\left(\\sqrt{\\sin^2\\!\\frac{\\varphi_2-\\varphi_1}{2}\n    + \\cos\\varphi_1 \\cos\\varphi_2 \\sin^2\\!\\frac{\\lambda_2-\\lambda_1}{2}}\\right)\n$$\n\nþar sem $\\varphi$ er breiddargráða, $\\lambda$ lengdargráða og $r \\approx 6371$ km. Mundu að\numbreyta gráðum í radíana.\n\n**Sannreyndu svarið.** Sæktu líka stöðvarnar án `active`-síunnar og berðu saman:\n\n1. Hver er næsta stöð þegar allar stöðvar eru með? Er hún enn í notkun?\n2. Hver er næsta **virka** stöðin, og hversu miklu munar á þeim?\n3. Hversu margar af 776 stöðvunum eru virkar? Hvað segir það þér um að treysta listanum óséðum?\n4. Forritið þitt á að sýna veðrið **núna**. Hvaða reit í svarinu þarftu að skoða til að vita\n   hvort stöð dugi í það?\n5. Ef þú vildir í staðinn bera saman veður í dag við veður fyrir 50 árum — væri sama stöð rétt?\n   Hvers vegna ekki?\n\n::: {.callout-important}\n## Sami lærdómur og í fyrri æfingunni\n\nÞjónustan skilar aflögðum stöðvum með þeim virku, jafn gildum á að líta. Ekkert í mælingunum\nsjálfum segir þér að stöð hafi hætt árið 1963 — það stendur í **lýsigögnunum**, í reitnum\n`ending`.\n\nÍ Hagstofuæfingunni réð `Tími` því hvað talan þýddi. Hér ræður `ending` því hvort stöðin sé\nnothæf. Í bæði skiptin eru það lýsigögnin, ekki mælingarnar, sem skera úr.\n:::\n\n::: {.callout-warning}\n## Hnitin þín geta snúið svarinu við\n\nMunurinn á tveimur næstu stöðvum er um **50 metrar** — minna en skekkjan sem þú færð með því að\nslá inn hnit „á að giska\" fyrir bygginguna.\n\nÞetta er ekki tilgáta: fyrsta útgáfa þessarar æfingar notaði ágiskuð hnit sem lágu 100 m sunnar\nen VR-II stendur í raun, og þá raðaðist listinn í **öfuga röð**.\n\nSkráðu því alltaf hvaða hnit þú notaðir og hvaðan þau komu. Það er forsenda þess að einhver\nannar fái sömu niðurstöðu.\n:::\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}